---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    app: load
spec:
  selector:
    matchLabels:
      app: load
  replicas: 1 
  template: 
    metadata:
      labels:
        app: load
    spec:
      containers:
      - env:
        - name: PATH1
          value: "/about"
        - name: PATH2
          value: "/register"
        - name: PATH3
          value: "/"
        - name: HOST
          value: "https://prateeks-blog.herokuapp.com"
        - name: LOAD_FILE
          value: "/config/locustfile.py" # for post requests use postRequest.py
        - name: SPAWN_RATE
          value: "10"
        - name: USERS
          value: "10"
        - name: RUN_TIME
          value: "10s"
        name: load-test
        image: prateekdegaons/locust-test:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: load
spec:
  type: NodePort
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: load
